steps:
  # 0. Copy environment file
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '${_ENV}', '.env']
    dir: 'backend'

  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}', '.']
    dir: 'backend'

  # 2. Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'buku-tukar',
        '--image',
        'gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}',
        '--timeout',
        '300s',
        '--region',
        'us-central1',
        '--allow-unauthenticated',
      ]

# HAPUS INI atau ganti jadi:
# options:
#   logging: CLOUD_LOGGING_ONLY

# Ganti jadi salah satu ini:
options:
  logging: LEGACY # atau hapus options sama sekali
